package installers

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func InstallClaude(daemonAddr string) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}
	claudeDir := filepath.Join(home, ".claude")
	if err := os.MkdirAll(claudeDir, 0o755); err != nil {
		return err
	}
	settingsPath := filepath.Join(claudeDir, "settings.json")
	cfgJSON, err := patchClaudeSettings(settingsPath, daemonAddr)
	if err != nil {
		return fmt.Errorf("patch claude settings: %w", err)
	}
	if err := os.WriteFile(settingsPath, cfgJSON, 0o644); err != nil {
		return fmt.Errorf("write claude settings: %w", err)
	}
	fmt.Println("Claude Code hooks installed.")
	fmt.Printf("  settings:  %s\n", settingsPath)
	fmt.Printf("  endpoint:  %s/api/v1/hooks/claude\n", daemonAddr)
	fmt.Println("\nStart the daemon with 'oc daemon', then open a Claude Code session. Messages will be recorded.")
	return nil
}

func InstallCodex(daemonAddr string) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}
	hooksDir := filepath.Join(home, ".opencontext", "collectors", "hooks")
	if err := os.MkdirAll(hooksDir, 0o755); err != nil {
		return err
	}
	scriptPath := filepath.Join(hooksDir, "codex.sh")
	script := fmt.Sprintf(`#!/usr/bin/env bash
# OpenContext hook adapter for Codex CLI — auto-generated by: oc collector codex install
INPUT=$(cat)
curl -sf -X POST %s/api/v1/hooks/codex \
  -H "Content-Type: application/json" \
  --data-raw "$INPUT" >/dev/null 2>&1 &
exit 0
`, daemonAddr)
	if err := os.WriteFile(scriptPath, []byte(script), 0o755); err != nil {
		return fmt.Errorf("write hook script: %w", err)
	}
	codexCfgDir := filepath.Join(home, ".codex")
	if err := os.MkdirAll(codexCfgDir, 0o755); err != nil {
		return err
	}
	codexHooksPath := filepath.Join(codexCfgDir, "hooks.json")
	cfgJSON, err := patchCodexHooks(codexHooksPath, scriptPath)
	if err != nil {
		return fmt.Errorf("patch codex hooks: %w", err)
	}
	if err := os.WriteFile(codexHooksPath, cfgJSON, 0o644); err != nil {
		return fmt.Errorf("write codex hooks: %w", err)
	}
	fmt.Println("Codex CLI hooks installed.")
	fmt.Printf("  hook script:  %s\n", scriptPath)
	fmt.Printf("  codex hooks:  %s\n", codexHooksPath)
	fmt.Printf("  endpoint:     %s/api/v1/hooks/codex\n", daemonAddr)
	fmt.Println("\nStart the daemon with 'oc daemon', then open a Codex session. Messages will be recorded.")
	fmt.Println("Note: Codex may prompt you to trust the hook on first run (/hooks to review).")
	return nil
}

func InstallCursor(daemonAddr string) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}
	cursorHooksDir := filepath.Join(home, ".cursor", "hooks")
	if err := os.MkdirAll(cursorHooksDir, 0o755); err != nil {
		return err
	}
	scriptPath := filepath.Join(cursorHooksDir, "oc-capture.sh")
	script := fmt.Sprintf(`#!/usr/bin/env bash
# OpenContext hook adapter for Cursor IDE — auto-generated by: oc collector cursor install
INPUT=$(cat)
curl -sf -X POST %s/api/v1/hooks/cursor \
  -H "Content-Type: application/json" \
  --data-raw "$INPUT" >/dev/null 2>&1 &
exit 0
`, daemonAddr)
	if err := os.WriteFile(scriptPath, []byte(script), 0o755); err != nil {
		return fmt.Errorf("write hook script: %w", err)
	}
	cursorCfgPath := filepath.Join(home, ".cursor", "hooks.json")
	cfgJSON, err := patchCursorHooks(cursorCfgPath)
	if err != nil {
		return fmt.Errorf("patch cursor hooks: %w", err)
	}
	if err := os.WriteFile(cursorCfgPath, cfgJSON, 0o644); err != nil {
		return fmt.Errorf("write cursor hooks: %w", err)
	}
	fmt.Println("Cursor IDE hooks installed.")
	fmt.Printf("  hook script:    %s\n", scriptPath)
	fmt.Printf("  cursor hooks:   %s\n", cursorCfgPath)
	fmt.Printf("  endpoint:       %s/api/v1/hooks/cursor\n", daemonAddr)
	fmt.Println("\nReload Cursor. Agent prompts and session starts will be recorded.")
	return nil
}

func InstallOpenCode(daemonAddr string) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}
	hooksDir := filepath.Join(home, ".opencontext", "collectors", "hooks")
	if err := os.MkdirAll(hooksDir, 0o755); err != nil {
		return err
	}
	scriptPath := filepath.Join(hooksDir, "opencode.sh")
	script := fmt.Sprintf(`#!/usr/bin/env bash
# OpenContext hook adapter for OpenCode — auto-generated by: oc collector opencode install
INPUT=$(cat)
curl -sf -X POST %s/api/v1/hooks/opencode \
  -H "Content-Type: application/json" \
  --data-raw "$INPUT" >/dev/null 2>&1 &
exit 0
`, daemonAddr)
	if err := os.WriteFile(scriptPath, []byte(script), 0o755); err != nil {
		return fmt.Errorf("write hook script: %w", err)
	}
	opencodeCfgDir := filepath.Join(home, ".config", "opencode")
	if err := os.MkdirAll(opencodeCfgDir, 0o755); err != nil {
		return err
	}
	opencodeCfgPath := filepath.Join(opencodeCfgDir, "hooks.json")
	cfgJSON, err := patchOpenCodeHooks(opencodeCfgPath, scriptPath)
	if err != nil {
		return fmt.Errorf("patch opencode hooks: %w", err)
	}
	if err := os.WriteFile(opencodeCfgPath, cfgJSON, 0o644); err != nil {
		return fmt.Errorf("write opencode hooks: %w", err)
	}
	fmt.Println("OpenCode hooks installed.")
	fmt.Printf("  hook script:     %s\n", scriptPath)
	fmt.Printf("  opencode hooks:  %s\n", opencodeCfgPath)
	fmt.Printf("  endpoint:        %s/api/v1/hooks/opencode\n", daemonAddr)
	fmt.Println("\nStart or restart OpenCode. User messages will be recorded.")
	return nil
}

func InstallShell(sensitivity int) error {
	if sensitivity < 1 || sensitivity > 2 {
		sensitivity = 1
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}
	ocBin, err := resolvedExecutable()
	if err != nil {
		return err
	}
	hooksDir := filepath.Join(home, ".opencontext", "collectors", "shell")
	if err := os.MkdirAll(hooksDir, 0o755); err != nil {
		return err
	}
	zshHook := shellHookZsh(ocBin, sensitivity)
	bashHook := shellHookBash(ocBin, sensitivity)
	if err := os.WriteFile(filepath.Join(hooksDir, "hooks.zsh"), []byte(zshHook), 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(hooksDir, "hooks.bash"), []byte(bashHook), 0o644); err != nil {
		return err
	}
	appendIfMissing(filepath.Join(home, ".zshrc"), "\n# OpenContext shell collector\nsource ~/.opencontext/collectors/shell/hooks.zsh\n", "hooks.zsh")
	appendIfMissing(filepath.Join(home, ".bashrc"), "\n# OpenContext shell collector\nsource ~/.opencontext/collectors/shell/hooks.bash\n", "hooks.bash")

	shell := detectShell()
	fmt.Println("Shell hooks installed.")
	fmt.Printf("  hooks dir:   %s\n", hooksDir)
	fmt.Printf("  shell:       %s (zsh and bash configs were checked)\n", shell)
	fmt.Printf("  sensitivity: L%d\n", sensitivity)
	fmt.Println("\nRestart your shell or source your shell config.")
	return nil
}

func patchClaudeSettings(cfgPath, daemonAddr string) ([]byte, error) {
	endpoint := strings.TrimRight(daemonAddr, "/") + "/api/v1/hooks/claude"
	ocEntry := map[string]any{
		"hooks": []map[string]any{{
			"type":    "http",
			"url":     endpoint,
			"timeout": 2,
		}},
	}
	entryJSON, _ := json.Marshal(ocEntry)

	topLevel := map[string]json.RawMessage{}
	if data, err := os.ReadFile(cfgPath); err == nil {
		_ = json.Unmarshal(data, &topLevel)
	}
	hooksMap := map[string]json.RawMessage{}
	if raw, ok := topLevel["hooks"]; ok {
		_ = json.Unmarshal(raw, &hooksMap)
	}
	for _, eventName := range []string{"UserPromptSubmit", "SessionStart"} {
		hooksMap[eventName] = prependJSONEntry(hooksMap[eventName], entryJSON, endpoint)
	}
	hooksRaw, err := json.Marshal(hooksMap)
	if err != nil {
		return nil, err
	}
	topLevel["hooks"] = hooksRaw
	return json.MarshalIndent(topLevel, "", "  ")
}

func patchCodexHooks(cfgPath, scriptPath string) ([]byte, error) {
	existing := map[string]json.RawMessage{}
	if data, err := os.ReadFile(cfgPath); err == nil {
		_ = json.Unmarshal(data, &existing)
	}
	ocEntry := map[string]any{"hooks": []map[string]string{{"type": "command", "command": scriptPath}}}
	entryJSON, _ := json.Marshal(ocEntry)
	for _, eventName := range []string{"UserPromptSubmit", "SessionStart"} {
		existing[eventName] = prependJSONEntry(existing[eventName], entryJSON, scriptPath)
	}
	return json.MarshalIndent(existing, "", "  ")
}

func patchCursorHooks(cfgPath string) ([]byte, error) {
	ocEntry := map[string]string{"command": "./hooks/oc-capture.sh"}
	entryJSON, _ := json.Marshal(ocEntry)
	topLevel := map[string]json.RawMessage{}
	if data, err := os.ReadFile(cfgPath); err == nil {
		_ = json.Unmarshal(data, &topLevel)
	}
	topLevel["version"] = json.RawMessage(`1`)
	for _, key := range []string{"beforeSubmitPrompt", "sessionStart"} {
		delete(topLevel, key)
	}
	hooksMap := map[string]json.RawMessage{}
	if raw, ok := topLevel["hooks"]; ok {
		_ = json.Unmarshal(raw, &hooksMap)
	}
	for _, key := range []string{"beforeSubmitPrompt", "sessionStart"} {
		hooksMap[key] = prependJSONEntry(hooksMap[key], entryJSON, "oc-capture")
	}
	hooksRaw, err := json.Marshal(hooksMap)
	if err != nil {
		return nil, err
	}
	topLevel["hooks"] = hooksRaw
	return json.MarshalIndent(topLevel, "", "  ")
}

func patchOpenCodeHooks(cfgPath, scriptPath string) ([]byte, error) {
	return patchCodexHooks(cfgPath, scriptPath)
}

func prependJSONEntry(existing json.RawMessage, entry json.RawMessage, dedupKey string) json.RawMessage {
	var items []json.RawMessage
	if existing != nil {
		_ = json.Unmarshal(existing, &items)
	}
	filtered := []json.RawMessage{entry}
	for _, item := range items {
		if !strings.Contains(string(item), dedupKey) {
			filtered = append(filtered, item)
		}
	}
	out, _ := json.Marshal(filtered)
	return out
}

func resolvedExecutable() (string, error) {
	exe, err := os.Executable()
	if err != nil {
		return "", fmt.Errorf("resolve oc binary path: %w", err)
	}
	if resolved, err := filepath.EvalSymlinks(exe); err == nil {
		exe = resolved
	}
	return exe, nil
}

func appendIfMissing(path, content, marker string) {
	data, _ := os.ReadFile(path)
	if strings.Contains(string(data), marker) {
		return
	}
	f, err := os.OpenFile(path, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0o644)
	if err != nil {
		fmt.Fprintf(os.Stderr, "warning: could not update %s: %v\n", path, err)
		return
	}
	defer f.Close()
	_, _ = f.WriteString(content)
}

func detectShell() string {
	shell := os.Getenv("SHELL")
	if idx := strings.LastIndex(shell, "/"); idx >= 0 {
		return shell[idx+1:]
	}
	if shell != "" {
		return shell
	}
	return "sh"
}

func shellHookZsh(ocBin string, sensitivity int) string {
	return fmt.Sprintf(`# OpenContext shell hooks — installed by: oc collector shell install
# Re-run install to update.
# oc binary: %s  sensitivity: %d

_oc_preexec() {
  _oc_cmd_start=$(date +%%s%%3N)
  _oc_cmd_input=$1
}

_oc_skip_cmd() {
  local cmd=$1
  [[ "$cmd" == " "* ]] && return 0
  local first="${cmd%%%% *}"
  case "$first" in
    clear|reset|ls|ll|la|pwd|cd|history|exit)
      [[ "$cmd" == "$first" ]] && return 0 ;;
  esac
  return 1
}

_oc_precmd() {
  local _oc_exit=$?
  local _oc_end
  _oc_end=$(date +%%s%%3N)
  local _oc_dur=$(( _oc_end - ${_oc_cmd_start:-$_oc_end} ))
  [[ -z "$_oc_cmd_input" ]] && return 0
  _oc_skip_cmd "$_oc_cmd_input" && { _oc_cmd_input=""; return 0; }
  %s collector shell push --command "$_oc_cmd_input" --exit-code "$_oc_exit" --duration-ms "$_oc_dur" --cwd "$PWD" --sensitivity %d &>/dev/null &!
  _oc_cmd_input=""
}

autoload -Uz add-zsh-hook
add-zsh-hook preexec _oc_preexec
add-zsh-hook precmd _oc_precmd
`, ocBin, sensitivity, ocBin, sensitivity)
}

func shellHookBash(ocBin string, sensitivity int) string {
	return fmt.Sprintf(`# OpenContext shell hooks — installed by: oc collector shell install
# oc binary: %s  sensitivity: %d

_oc_preexec() {
  _oc_cmd_start=$(date +%%s%%3N 2>/dev/null || echo 0)
  _oc_cmd_input=$BASH_COMMAND
}

_oc_skip_cmd() {
  local cmd=$1
  [[ "$cmd" == " "* ]] && return 0
  local first="${cmd%%%% *}"
  case "$first" in
    clear|reset|ls|ll|la|pwd|cd|history|exit)
      [[ "$cmd" == "$first" ]] && return 0 ;;
  esac
  return 1
}

_oc_precmd() {
  local _oc_exit=$?
  local _oc_end
  _oc_end=$(date +%%s%%3N 2>/dev/null || echo 0)
  local _oc_dur=$(( _oc_end - ${_oc_cmd_start:-0} ))
  [[ -z "$_oc_cmd_input" ]] && return 0
  [[ "$_oc_cmd_input" == "_oc_precmd" ]] && return 0
  _oc_skip_cmd "$_oc_cmd_input" && { _oc_cmd_input=""; return 0; }
  ( %s collector shell push --command "$_oc_cmd_input" --exit-code "$_oc_exit" --duration-ms "$_oc_dur" --cwd "$PWD" --sensitivity %d &>/dev/null & )
  _oc_cmd_input=""
}

trap '_oc_preexec "$BASH_COMMAND"' DEBUG
PROMPT_COMMAND="_oc_precmd${PROMPT_COMMAND:+;$PROMPT_COMMAND}"
`, ocBin, sensitivity, ocBin, sensitivity)
}
